name: wofs_albers
description: Historic Flood Mapping Water Observations from Space
managed: True
metadata_type: eo
metadata:
  product_type: wofs
  format: 
    name: NetCDF
storage:
    crs: EPSG:3577
    resolution:
        x: 25
        y: -25
    tile_size:
        x: 100000.0
        y: 100000.0
    driver: NetCDF CF
    dimension_order: [time, y, x]
    chunking:
        x: 200
        y: 200
        time: 1   
measurements:
  - name: water
    dtype: uint8
    nodata: 1
    units: '1'
    flags_definition:
      type:                 # TODO: change this label..
        bits: [0,1,2,3,4,5,6,7]
        values: 
            128: clear_wet
            0: clear_dry
        description: Classification result with unclear observations masked out
