source_type: ls7_nbar_albers
output_type: ls7_ndvi_albers
version: ${version}

description: Landsat 7 Normalised Difference Vegetation Index 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)
product_type: ndvi

location: '/g/data/fk4/datacube/002/'
file_path_template: 'LS7_ETM_NDVI/{tile_index[0]}_{tile_index[1]}/LS7_ETM_NDVI_3577_{tile_index[0]}_{tile_index[1]}_{start_time}.nc'
global_attributes:
  title: "Normalised Difference Vegetation Index 25 v2"
  summary: |
    Live green plants absorb solar radiation in the photosynthetically active radiation (PAR) spectral region, which they use as a source of energy in the process of photosynthesis. Leaf cells have also evolved to reflect, scatter and re-emit solar radiation in the near-infrared spectral region. The pigment in plant leaves, chlorophyll, strongly absorbs visible light (from 0.4 to 0.7 micrometres) for use in photosynthesis. The cell structure of the leaves, on the other hand, strongly reflects near-infrared light (from 0.7 to 1.1 micrometres). Hence, live green plants appear relatively dark in the PAR and relatively bright in the near-infrared.

    By contrast, clouds and snow tend to be rather bright in the red (as well as other visible wavelengths) and quite dark in the near-infrared.

    The Normalised Difference Vegetation Index  (NDVI) is calculated as follows

    (NIR-RED)/(NIR+RED) - where RED and NIR stand for the spectral reflectance measurements acquired in the red and near-infrared regions, respectively.

    NDVI values range between -1 and +1, and have been scaled by 10000 to be stored as intgers between -10000 and +10000.

    Negative values of NDVI (values between 0 and -1) usually correspond to non vegetation targets such as water.

    Values close to zero (-0.1 to 0.1) generally correspond to barren areas of rock, sand, or snow. Low, positive values usually represent shrub and grassland (approximately 0.2 to 0.4), while high values are indicative of healthy crops or dense vegetation such as temperate and tropical rainforests (values approaching 1).

    First described in Tucker (1979) the NDVI has been widely used as a vegetation index to characterise the amount of vegetation on the Earths surface. The study by Carlson and Ripley (1997) is widely cited and describes the relationship between NDVI, fractional vegetation cover and leaf area index.

  institution: "Commonwealth of Australia (Geoscience Australia)"
  instrument: ETM
  keywords: AU/GA,NASA/GSFC/SED/ESD/LANDSAT,REFLECTANCE,ETM+,TM,OLI,EARTH SCIENCE
  keywords_vocabulary: GCMD
  platform: LANDSAT-7
  product_version: 2
  publisher_email: "earth.observation@ga.gov.au"
  publisher_name: "Section Leader, Operations Section, NEMO, Geoscience Australia"
  publisher_url: 'http://www.ga.gov.au'
  license: CC BY Attribution 4.0 International License
  coverage_content_type: "physicalMeasurement"
  cdm_data_type: "Grid"
  product_suite: "NDVI 25m"
  acknowledgment: Landsat data is provided by the United States Geological Survey (USGS) through direct reception of the data at Geoscience Australias satellite reception facility or download.
  references: |
    - Carlson, T.N. and Ripley, D.A., 1997. On the relation between NDVI, fractional vegetation cover, and leaf area index. Remote sensing of Environment, 62(3), pp.241-252.
    - Roy, D.P., Kovalskyy, V., Zhang, H.K., Vermote, E.F., Yan, L., Kumar, S.S. and Egorov, A., 2016. Characterization of Landsat-7 to Landsat-8 reflective wavelength and normalized difference vegetation index continuity. Remote Sensing of Environment.
    - Tucker, C.J. (1979) 'Red and Photographic Infrared Linear Combinations for Monitoring Vegetation', Remote Sensing of Environment, 8(2),127-150
    - Zhu, Z., Fu, Y., Woodcock, C.E., Olofsson, P., Vogelmann, J.E., Holden, C., Wang, M., Dai, S. and Yu, Y., 2016. Including land cover change in analysis of greenness trends using all available Landsat 5, 7, and 8 images: A case study from Guangzhou, China (2000-2014). Remote Sensing of Environment.
storage:
  driver: NetCDF CF

  crs: EPSG:3577
  tile_size:
          x: 100000.0
          y: 100000.0
  resolution:
          x: 25
          y: -25
  chunking:
      x: 200
      y: 200
      time: 1
  dimension_order: ['time', 'y', 'x']

measurements:
    - name: ndvi
      units: '1'
      dtype: int16
      nodata: -32768
      zlib: True
      fletcher32: True
      attrs:
          long_name: "Normalised Difference Vegetation Index"
          alias: "greenness"
