name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish_pypi:
    if: github.repository == 'GeoscienceAustralia/wofs'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # Package should have already been built in push action

      - name: Install Twine
        run: |
          python -m pip install --upgrade twine
          python -m pip freeze

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
